import io
from gestor import *
from shutil import *
import os

def basicTag(): ##### DEFINING BASIC TAG TEMPLATE #####
    try:
        f = open("YOUR_STUFF/basic.html","w")
        f.write("<!DOCTYPE html> <!-- CHANGE WHATEVER YOU WANT -->\r\n<html>\r\n<head>\r\n    <title>Title</title>\r\n"\
            "   <link href=\"basic.css\" rel=\"stylesheet\">\r\n</head>\r\n<body>\r\n    <h1>Hello World</h1>\r\n</body>\r\n"\
            "</html>")
        f.close()
        f2 = open("YOUR_STUFF/basic.css", "w")
        f2.write("/* YOUR CSS HERE */")
        f2.close()
        print("\033[1;32m\r\n[*] Template created succesfully... Have fun! ;)\033[1;m\r\n")
    except:
        print ("\r\n\033[1;41m[!] Error... can't create the file\033[1;m\r\n")
def simpleBar():
    try:
        f = open("YOUR_STUFF/simple_bar.html", "w")
        f.write('<!DOCTYPE html> <!-- CHANGE WHATEVER YOU WANT -->\r\n' \
            '<html> \r\n'
            '<head>\r\n'
              '     <title>Title</title>\r\n'
              '     <link href="simple_bar.css" rel="stylesheet">\r\n'
              '     <link href="https://fonts.googleapis.com/css?family=Lalezar" rel="stylesheet"> <!-- Change your font -->\r\n'
            '</head>\r\n'
            '<body>\r\n'
             '  <nav class="nav-main">\r\n'
                '       <div class="logo">Home</div>\r\n'
                '       <ul>\r\n'
                  '         <li>\r\n'
                      '         <a href="#" class="nav-item">Info</a>\r\n'
                  '         </li>\r\n'
                  '         <li>\r\n'
                      '         <a href="#" class="nav-item">Contacts</a>\r\n'
                  '         </li>\r\n'
                  '         <li>\r\n'
                      '         <a href="#" class="nav-item">Products</a>\r\n'
                  '         </li>\r\n'
                '     </ul>\r\n'
              ' </nav>\r\n'
              ' <div class="content">\r\n\r\n'

              ' </div>\r\n'
            '</body>\r\n'
        '</html>\r\n')
        f.close()
        f2 = open("YOUR_STUFF/simple_bar.css", "w")
        f2.write('/* CHANGE WHATEVER YOU WANT */\r\nbody, html { \r\n' \
              'margin:0;\r\n'
              'font-family: "Lalezar", cursive;\r\n'
              'animation-name: page;\r\n'
              '-webkit-animation-name: page;\r\n'
              '-moz-animation-name: page;\r\n'
              'animation-duration: 1.0s;\r\n'
              '-webkit-animation-duration: 1.0s;\r\n'
              '-moz-animation-duration: 1.0s;\r\n'
            '}\r\n\r\n'
            '@keyframes page{ /*PAGE TRANSITION */\r\n'
            'from{\r\n'
            'opacity: 0;\r\n'
            '}to{\r\n'
            'opacity: 1.0;\r\n'
            '}\r\n'
            '}\r\n'
            '@-webkit-keyframes page{\r\n'
            'from{\r\n'
            'opacity: 0;\r\n'
            '}to{\r\n'
            'opacity: 1.0;\r\n'
            '}\r\n'
            '}\r\n'
            '.content{\r\n'
              'padding: 30px;\r\n'
            '}\r\n\r\n'

            '.nav-main {\r\n'
              'width: 100%;\r\n'
              'background-color: #212121;\r\n'
              'height: 70px;\r\n'
              'color: #fff;\r\n'
            '}\r\n\r\n'

            '.logo {\r\n'
              'float: left;\r\n'
              'height: 40px;\r\n'
              'padding: 15px 30px;\r\n'
              'font-size: 2.5em;\r\n'
              'line-height: 40px\r\n'
            '}\r\n\r\n'

            '.nav-main > ul {\r\n'
              'margin: 0;\r\n'
              'padding: 0;\r\n'
              'float: left;\r\n'
              'list-style-type: none;\r\n'
            '}\r\n\r\n'

            '.nav-main > ul > li {\r\n'
              'float: left;\r\n'
            '}\r\n\r\n'

            '.nav-item {\r\n\r\n'
              'display: inline-block;\r\n'
             'padding: 15px 20px;\r\n'
              'height: 40px;\r\n'
              'line-height: 40px;\r\n'
              'color: #fff;\r\n'
              'text-decoration: none;\r\n'
            '}\r\n'

            '.nav-item:hover{\r\n'
             'background-color: #424242;\r\n'
            '}\r\n\r\n')
        f2.close()
        print("\033[1;32m\r\n[*] Template created succesfully... Have fun! ;)\033[1;m\r\n")
    except:
        print ("\r\n\033[1;41m[!] Error... can't create the file\033[1;m\r\n")

def dropBar(): ###DROPDOWN BAR####
    try :
        f = open("YOUR_STUFF/drop.html", "w")
        f.write('<!DOCTYPE html> <!-- THIS IS THE DROPDOWN BAR... ENJOY XD -->\r\n' \
            '<html> \r\n'
            '<head>\r\n'
              '     <title>Title</title>\r\n'
              '     <link href="drop.css" rel="stylesheet">\r\n'
              '     <link href="https://fonts.googleapis.com/css?family=Lalezar" rel="stylesheet"> <!-- Change your font -->\r\n'
            '</head>\r\n'
            '<body>\r\n'
             '  <nav class="nav-main">\r\n'
                '       <div class="logo">Home</div>\r\n'
                '       <ul>\r\n'
                  '         <li>\r\n'
                      '         <a href="#" class="nav-item">Info</a>\r\n'
                      '         <div class="nav-content">\r\n'
                        '           <div class="nav-sub">\r\n'
                          '             <ul>\r\n'
                            '               <li><a href="#">About</a></li>\r\n'
                            '               <li><a href="#">Costs</a></li>\r\n'
                            '               <li><a href="#">Address</a></li>\r\n'
                          '             </ul>\r\n'
                        '           </div>\r\n'
                      '         </div>\r\n'
                  '         </li>\r\n'
                  '         <li>\r\n'
                      '         <a href="#" class="nav-item">Contacts</a>\r\n'
                      '         <div class="nav-content">\r\n'
                        '           <div class="nav-sub">\r\n'
                          '             <ul>\r\n'
                            '               <li><a href="#">Email</a></li>\r\n'
                            '               <li><a href="#">Facebook</a></li>\r\n'
                            '               <li><a href="#">Instagram</a></li>\r\n'
                          '             </ul>\r\n'
                        '           </div>\r\n'
                      '         </div>\r\n'
                  '         </li>\r\n'
                  '         <li>\r\n'
                      '         <a href="#" class="nav-item">Products</a>\r\n'
                      '         <div class="nav-content">\r\n'
                        '           <div class="nav-sub">\r\n'
                          '             <ul>\r\n'
                            '               <li><a href="#">About</a></li>\r\n'
                            '               <li><a href="#">Costs</a></li>\r\n'
                            '               <li><a href="#">Type</a></li>\r\n'
                          '             </ul>\r\n'
                        '           </div>\r\n'
                      '         </div>\r\n'
                  '         </li>\r\n'
                '     </ul>\r\n'
              ' </nav>\r\n'
              ' <div class="content">\r\n\r\n'

              ' </div>\r\n'
            '</body>\r\n'
        '</html>\r\n')
        f.close()
        f2 = open("YOUR_STUFF/drop.css", "w")
        f2.write('/* CHANGE WHATEVER YOU WANT */\r\nbody, html { \r\n' \
              'margin:0;\r\n'
              'font-family: "Lalezar", cursive;\r\n'
              'animation-name: page;\r\n'
              '-webkit-animation-name: page;\r\n'
              '-moz-animation-name: page;\r\n'
              'animation-duration: 1.0s;\r\n'
              '-webkit-animation-duration: 1.0s;\r\n'
              '-moz-animation-duration: 1.0s;\r\n'
            '}\r\n\r\n'
             '@keyframes page{ /*PAGE TRANSITION */\r\n'
             'from{\r\n'
             'opacity: 0;\r\n'
             '}to{\r\n'
             'opacity: 1.0;\r\n'
             '}\r\n'
             '}\r\n'
             '@-webkit-keyframes page{\r\n'
             'from{\r\n'
             'opacity: 0;\r\n'
             '}to{\r\n'
             'opacity: 1.0;\r\n'
             '}\r\n'
             '}\r\n'
            '.content{\r\n'
              'padding: 30px;\r\n'
            '}\r\n\r\n'

            '.nav-main {\r\n'
              'width: 100%;\r\n'
              'background-color: #2196f3;\r\n'
              'height: 70px;\r\n'
              'color: #fff;\r\n'
            '}\r\n\r\n'

            '.logo {\r\n'
              'float: left;\r\n'
              'height: 40px;\r\n'
              'padding: 15px 30px;\r\n'
              'font-size: 2.5em;\r\n'
              'line-height: 40px\r\n'
            '}\r\n\r\n'

            '.nav-main > ul {\r\n'
              'margin: 0;\r\n'
              'padding: 0;\r\n'
              'float: left;\r\n'
              'list-style-type: none;\r\n'
            '}\r\n\r\n'

            '.nav-main > ul > li {\r\n'
              'float: left;\r\n'
            '}\r\n\r\n'

            '.nav-item {\r\n\r\n'
              'display: inline-block;\r\n'
             'padding: 15px 20px;\r\n'
              'height: 40px;\r\n'
              'line-height: 40px;\r\n'
              'color: #fff;\r\n'
              'text-decoration: none;\r\n'
            '}\r\n'

            '.nav-item:hover{\r\n'
             'background-color: #1565c0;\r\n'
            '}\r\n\r\n'
            '.nav-content{\r\n'
             'position: absolute;\r\n'
              'top: 70px;\r\n'
              'overflow: hidden;\r\n'
              'background-color: #1565c0;\r\n'
              'color: #fff;\r\n'
              'max-height: 0;\r\n'
            '}\r\n\r\n'

            '.nav-content a {\r\n'
              'color: #fff;\r\n'
              'text-decoration: none;\r\n'
            '}\r\n'
            '.nav-content a:hover{\r\n'
              'text-decoration: underline;\r\n'
            '}\r\n\r\n'

            '.nav-sub {\r\n'
              'padding: 20px;\r\n'
            '}\r\n\r\n'

            '.nav-sub ul {\r\n'
              'padding: 0;\r\n'
              'margin: 0;\r\n'
              'list-style-type: none;\r\n'
            '}\r\n\r\n'

            '.nav-sub ul li a {\r\n'
              'display: inline-block;\r\n'
              'padding: 5px 0;\r\n'
            '}\r\n\r\n'

            '.nav-item:focus{\r\n'
              'background-color: #1565c0;\r\n'
            '}\r\n\r\n'

            '.nav-item:focus ~ .nav-content {\r\n'
              'max-height: 400px;\r\n'
              'transition: max-height 0.4s ease-in;\r\n'
              '-webkit-transition: max-height 0.4s ease-in;\r\n'
              '-moz-transition: max-height 0.4s ease-in;\r\n'
            '}\r\n\r\n')

        f2.close()
        print("\033[1;32m\r\n[*] Template created succesfully... Have fun! ;)\033[1;m\r\n")
    except:
        print ("\r\n\033[1;41m[!] Error... can't create the file\033[1;m\r\n")

def respBar():
    try :
        f = open("YOUR_STUFF/resp_bar.html", "w")
        f.write('<!DOCTYPE html> <!-- THIS IS THE RESPONSIVE MENU BAR, TRY TO RESIZE YOUR WINDOW... IT\'S MAGIC XD -->\r\n' \
            '<html>\r\n'
            '<head>\r\n'
            '     <title>Responsive Bar</title>\r\n'
            '     <link href="resp_bar.css" rel="stylesheet"> <!-- CSS -->\r\n'
            '     <link href="https://fonts.googleapis.com/css?family=Lalezar" rel="stylesheet"> <!--FONT-->\r\n'
            '     <meta name="viewport" content="width=device-width, initial-scale=1.0"> <!-- RESPONSIVE -->\r\n'
            '</head>\r\n'
            '<body>\r\n'
            '   <nav class="nav-main">\r\n'
            '      <a href="#drop"><img src="src/menu.png" width="35px" height="35px" id="ham" class="menu"></a> <!-- MOBILE BAR -->\r\n'
            '       <div class="logo">Welcome\r\n'
            '         <div class="nav-content" id="drop">\r\n'
            '           <div class="nav-sub">\r\n'
            '             <ul>\r\n'
            '               <li><a href="#">Menu</a></li>\r\n'
            '               <li><a href="#">Admin</a></li>\r\n'
            '               <li><a href="#">Users</a></li>\r\n'
            '           </div>\r\n'
            '           <li><a href="#"><img src="src/close.png" width="40px" height="40px" class="close"></a></li>\r\n'
            '           </ul>\r\n'
            '         </div>\r\n'
            '       </div>\r\n'
            '       <ul>\r\n'
            '         <li>\r\n'
            '         <a href="#" class="nav-item">Menu</a>\r\n'
            '         </li>\r\n'
            '         <li>\r\n'
            '         <a href="#" class="nav-item">Admin</a>\r\n'
            '         </li>\r\n'
            '         <li>\r\n'
            '         <a href="#" class="nav-item">Users</a>\r\n'
            '         </li>\r\n'
            '     </ul>\r\n'
            ' </nav>\r\n'
            ' <div class="content">\r\n'
            '\r\n'
            ' </div>\r\n'
            '</body>\r\n'
            '</html>')
        f.close()
        f2 = open("YOUR_STUFF/resp_bar.css", "w")
        f2.write('body, html {\r\n' \
            'margin:0;\r\n'
            'font-family: "Lalezar", cursive;\r\n'
            'animation-name: page;\r\n'
            'height: 3000px;\r\n'
            '-webkit-animation-name: page; /* PAGE TRANSITION */\r\n'
            '-moz-animation-name: page;\r\n'
            'animation-duration: 1.0s;\r\n'
            '-webkit-animation-duration: 1.0s;\r\n'
            '-moz-animation-duration: 1.0s;\r\n'
            '}\r\n'
            '@keyframes page{\r\n'
            'from{\r\n'
            'opacity: 0;\r\n'
            '}to{\r\n'
            'opacity: 1.0;\r\n'
            '}\r\n'
            '}\r\n'
            '@-webkit-keyframes page{\r\n'
            'from{\r\n'
            'opacity: 0;\r\n'
            '}to{\r\n'
            'opacity: 1.0;\r\n'
            '}\r\n'
            '}\r\n'
            '.drop{\r\n'
             'display:none;\r\n'
            ' z-index:20;\r\n'
            '}\r\n\r\n'
            '.nav-main {\r\n'
            'width: 100%;\r\n'
            'background-color: #212121;\r\n'
            'height: 70px;\r\n'
            'color: #fff;\r\n'
            '}\r\n\r\n'
            '.logo {\r\n'
            'float: left;\r\n'
            'height: 40px;\r\n'
            'padding: 15px 30px;\r\n'
            'font-size: 2.5em;\r\n'
            'line-height: 40px;\r\n'
            '}\r\n\r\n'
            '.nav-main > ul {\r\n'
            'margin: 0;\r\n'
            'padding: 0;\r\n'
            'float: left;\r\n'
            'list-style-type: none;\r\n'
            '}\r\n\r\n'
            '.nav-main > ul > li {\r\n'
            'float: left;\r\n'
            '}\r\n\r\n'
            '.nav-item {\r\n'
            'display: inline-block;\r\n'
            'padding: 15px 20px;\r\n'
            'height: 40px;\r\n'
            'line-height: 40px;\r\n'
            'color: #fff;\r\n'
            'text-decoration: none;\r\n\r\n'
            '}\r\n'
            '.nav-item:hover{\r\n'
            'background-color: #424242;\r\n'
            '}\r\n'
            '.mobile {\r\n'
            'z-index:20;\r\n'
            'display:none;\r\n'
            '}\r\n'
            '.mob-title {\r\n'
            'z-index:20;\r\n'
            'display:none;\r\n'
            '}\r\n'
            '.nav-content{\r\n'
              'display: none;\r\n'
              'z-index: 20;\r\n'
            '}\r\n'
            '#ham {\r\n'
             'display: none;\r\n'
              'z-index: 20;\r\n'
            '}\r\n'
            '#box {\r\n'
            'display:none;\r\n'
            'z-index:20;\r\n'
            '}\r\n\r\n'
            '@media screen and (max-width:500px){ /* RESPONSIVE */\r\n'
               '.nav-main {\r\n'
                'height: 60px;\r\n'
                'display:block;\r\n'
            '}\r\n'
              '.nav-main > ul {\r\n'
                'display: none;\r\n'
                'z-index: 20;}\r\n'
              '.nav-main > ul > li {\r\n'
                'display:none;\r\n'
                'z-index:20;}\r\n'
              '.nav-item {\r\n'
                'display:none;\r\n'
                'z-index:20;}\r\n'
              '.logo{\r\n'
               'margin-right:auto;\r\n'
               'margin-left:auto;\r\n'
               'color: #fff;\r\n'
               'height: 40px;\r\n'
               'width:50%;\r\n'
               'padding-top:12px;\r\n'
            '}\r\n'
             '#drop{\r\n'
                'display: block;\r\n'
                'overflow: hidden;\r\n'
                'background-color: #212121;\r\n'
                'color: #fff;\r\n'
                'font-size: 0.5em;\r\n'
                'float: right;\r\n'
                'position: absolute;\r\n'
                'left:72%;\r\n'
                'max-height: 0;\r\n'
              '}\r\n'
              '.close{\r\n'
                'float:right;\r\n'
              '}\r\n'
              '#drop a {\r\n'
                'color: #fff;\r\n'
                'text-decoration: none;\r\n'
              '}\r\n'
              '#drop a:hover{\r\n'
                'text-decoration: underline;\r\n'
              '}\r\n'
              '.nav-sub {\r\n'
                'padding: 20px;\r\n'
              '}\r\n'
              '.nav-sub ul {\r\n'
                'padding: 0;\r\n'
                'margin: 0;\r\n'
                'list-style-type: none;\r\n'
              '}\r\n'
              '.nav-sub ul li a {\r\n'
                'display: inline-block;\r\n'
                'padding: 5px 0;\r\n'
                'float: right;\r\n'
              '}\r\n'
              '#ham {\r\n'
                'position: absolute;\r\n'
                'z-index: 5;\r\n'
                'display:flex;\r\n'
                'left: 80%;\r\n'
                'padding-top: 12px;\r\n'
              '}\r\n'
               '#drop:target{\r\n'
                'max-height: 400px;\r\n'
                'transition: max-height 0.4s ease-in;\r\n'
                '-webkit-transition: max-height 0.4s ease-in;\r\n'
                '-moz-transition: max-height 0.4s ease-in;\r\n'
            '}\r\n'
            '}\r\n')
        f2.close()
        print("\033[1;32m\r\n[*] Template created succesfully... Don't forget to copy the \033[1;45m'src'\033[1;m\033[1;32m folder where you move the template! ;)\033[1;m\r\n")
    except:
        print ("\r\n\033[1;41m[!] Error... can't create the file\033[1;m\r\n")
def respStick():
    try :
        f = open("YOUR_STUFF/respSticky.html", "w")
        f.write('<!DOCTYPE html> <!-- THIS IS THE RESPONSIVE STICKY MENU BAR... YEY ;) -->\r\n' \
            '<html>\r\n'
            '<head>\r\n'
            '     <title>Responsive Sticky Bar</title>\r\n'
            '     <link href="respSticky.css" rel="stylesheet"> <!-- CSS -->\r\n'
            '     <link href="https://fonts.googleapis.com/css?family=Lalezar" rel="stylesheet"> <!--FONT-->\r\n'
            '      <script type="text/javascript" src="http://ajax.googleapis.com/ajax/libs/jquery/1.4.2/jquery.min.js"></script> <!-- JQUERY -->\r\n'
            '      <script type="text/javascript" src="src/jquery.sticky.js"></script> <!-- STICKY FRAMEWORK -->\r\n'
            '      <script type="text/javascript" src="respSticky.js"></script> <!--  JAVASCRIPT --> \r\n'
            '     <meta name="viewport" content="width=device-width, initial-scale=1.0"> <!-- RESPONSIVE -->\r\n'
            '</head>\r\n'
            '<body>\r\n'
            '<div id="header">\r\n'
            '   <nav class="nav-main">\r\n'
            '      <a href="#drop"><img src="src/menu.png" width="35px" height="35px" id="ham" class="menu"></a> <!-- MOBILE BAR -->\r\n'
            '       <div class="logo">Welcome\r\n'
            '         <div class="nav-content" id="drop">\r\n'
            '           <div class="nav-sub">\r\n'
            '             <ul>\r\n'
            '               <li><a href="#">Menu</a></li>\r\n'
            '               <li><a href="#">Admin</a></li>\r\n'
            '               <li><a href="#">Users</a></li>\r\n'
            '           </div>\r\n'
            '           <li><a href="#"><img src="src/close.png" width="40px" height="40px" class="close"></a></li>\r\n'
            '           </ul>\r\n'
            '         </div>\r\n'
            '       </div>\r\n'
            '       <ul>\r\n'
            '         <li>\r\n'
            '         <a href="#" class="nav-item">Menu</a>\r\n'
            '         </li>\r\n'
            '         <li>\r\n'
            '         <a href="#" class="nav-item">Admin</a>\r\n'
            '         </li>\r\n'
            '         <li>\r\n'
            '         <a href="#" class="nav-item">Users</a>\r\n'
            '         </li>\r\n'
            '     </ul>\r\n'
            ' </nav>\r\n'
            '</div>\r\n'
            ' <div class="content">\r\n'
            '\r\n'
            ' </div>\r\n'
            '</body>\r\n'
            '</html>')
        f.close()
        f2 = open("YOUR_STUFF/respSticky.css", "w")
        f2.write('body, html {\r\n' \
            'margin:0;\r\n'
            'font-family: "Lalezar", cursive;\r\n'
            'animation-name: page;\r\n'
            'height: 3000px;\r\n'
            '-webkit-animation-name: page; /* PAGE TRANSITION */\r\n'
            '-moz-animation-name: page;\r\n'
            'animation-duration: 1.0s;\r\n'
            '-webkit-animation-duration: 1.0s;\r\n'
            '-moz-animation-duration: 1.0s;\r\n'
            '}\r\n'
            '@keyframes page{\r\n'
            'from{\r\n'
            'opacity: 0;\r\n'
            '}to{\r\n'
            'opacity: 1.0;\r\n'
            '}\r\n'
            '}\r\n'
            '@-webkit-keyframes page{\r\n'
            'from{\r\n'
            'opacity: 0;\r\n'
            '}to{\r\n'
            'opacity: 1.0;\r\n'
            '}\r\n'
            '}\r\n'
            '#header{\r\n'
              'margin:0;\r\n'
              'z-index:40;\r\n'
            '}\r\n'
            '.drop{\r\n'
             'display:none;\r\n'
            ' z-index:20;\r\n'
            '}\r\n\r\n'
            '.nav-main {\r\n'
            'width: 100%;\r\n'
            'background-color: #212121;\r\n'
            'height: 70px;\r\n'
            'color: #fff;\r\n'
            '}\r\n\r\n'
            '.logo {\r\n'
            'float: left;\r\n'
            'height: 40px;\r\n'
            'padding: 15px 30px;\r\n'
            'font-size: 2.5em;\r\n'
            'line-height: 40px;\r\n'
            '}\r\n\r\n'
            '.nav-main > ul {\r\n'
            'margin: 0;\r\n'
            'padding: 0;\r\n'
            'float: left;\r\n'
            'list-style-type: none;\r\n'
            '}\r\n\r\n'
            '.nav-main > ul > li {\r\n'
            'float: left;\r\n'
            '}\r\n\r\n'
            '.nav-item {\r\n'
            'display: inline-block;\r\n'
            'padding: 15px 20px;\r\n'
            'height: 40px;\r\n'
            'line-height: 40px;\r\n'
            'color: #fff;\r\n'
            'text-decoration: none;\r\n\r\n'
            '}\r\n'
            '.nav-item:hover{\r\n'
            'background-color: #424242;\r\n'
            '}\r\n'
            '.nav-content{\r\n'
              'display: none;\r\n'
              'z-index: 20;\r\n'
            '}\r\n'
            '#ham {\r\n'
             'display: none;\r\n'
              'z-index: 20;\r\n'
            '}\r\n'
            '#box {\r\n'
            'display:none;\r\n'
            'z-index:20;\r\n'
            '}\r\n\r\n'
            '@media screen and (max-width:500px){ /* RESPONSIVE */\r\n'
               '.nav-main {\r\n'
                'height: 60px;\r\n'
                'display:block;\r\n'
            '}\r\n'
              '.nav-main > ul {\r\n'
                'display: none;\r\n'
                'z-index: 20;}\r\n'
              '.nav-main > ul > li {\r\n'
                'display:none;\r\n'
                'z-index:20;}\r\n'
              '.nav-item {\r\n'
                'display:none;\r\n'
                'z-index:20;}\r\n'
              '.logo{\r\n'
               'margin-right:auto;\r\n'
               'margin-left:auto;\r\n'
               'color: #fff;\r\n'
               'height: 40px;\r\n'
               'width:50%;\r\n'
               'padding-top:12px;\r\n'
            '}\r\n'
             '#drop{\r\n'
                'display: block;\r\n'
                'overflow: hidden;\r\n'
                'background-color: #212121;\r\n'
                'color: #fff;\r\n'
                'font-size: 0.5em;\r\n'
                'float: right;\r\n'
                'position: absolute;\r\n'
                'left:72%;\r\n'
                'max-height: 0;\r\n'
              '}\r\n'
              '#drop a {\r\n'
                'color: #fff;\r\n'
                'text-decoration: none;\r\n'
              '}\r\n'
              '#drop a:hover{\r\n'
                'text-decoration: underline;\r\n'
              '}\r\n'
              '.nav-sub {\r\n'
                'padding: 20px;\r\n'
              '}\r\n'
              '.nav-sub ul {\r\n'
                'padding: 0;\r\n'
                'margin: 0;\r\n'
                'list-style-type: none;\r\n'
              '}\r\n'
              '.nav-sub ul li a {\r\n'
                'display: inline-block;\r\n'
                'padding: 5px 0;\r\n'
                'float: right;\r\n'
              '}\r\n'
              '#ham {\r\n'
                'position: absolute;\r\n'
                'z-index: 5;\r\n'
                'display:flex;\r\n'
                'left: 80%;\r\n'
                'padding-top: 12px;\r\n'
              '}\r\n'
              '.close{\r\n'
                'float:right;\r\n'
              '}\r\n'
               '#drop:target{\r\n'
                'max-height: 400px;\r\n'
                'transition: max-height 0.4s ease-in;\r\n'
                '-webkit-transition: max-height 0.4s ease-in;\r\n'
                '-moz-transition: max-height 0.4s ease-in;\r\n'
            '}\r\n'
            '}\r\n')
        f2.close()
        f3 = open("YOUR_STUFF/respSticky.js", "w")
        f3.write('$(window).load(function(){\r\n' \
              '     $("#header").sticky({ topSpacing: 0 });\r\n'
            '});')
        f3.close()
        print("\033[1;32m\r\n[*] Template created succesfully... Don't forget to copy the \033[1;45m'src'\033[1;m\033[1;32m folder where you move the template! ;)\033[1;m\r\n")
    except:
        print ("\r\n\033[1;41m[!] Error... can't create the file\033[1;m\r\n")
def stickyBar():
    try :
        f = open("YOUR_STUFF/sticky.html", "w")
        f.write('<!DOCTYPE html> <!--  STICKY LIKE YOUR YOUR ASS IN THAT CHAIR ;) -->\r\n' \
            '<html>\r\n'
            '<head>\r\n'
            '     <title>Sticky Bar</title>\r\n'
            '     <link href="sticky.css" rel="stylesheet"> <!-- CSS -->\r\n'
            '     <link href="https://fonts.googleapis.com/css?family=Lalezar" rel="stylesheet"> <!--FONT-->\r\n'
            '      <script type="text/javascript" src="http://ajax.googleapis.com/ajax/libs/jquery/1.4.2/jquery.min.js"></script> <!-- JQUERY -->\r\n'
            '      <script type="text/javascript" src="src/jquery.sticky.js"></script> <!-- STICKY FRAMEWORK -->\r\n'
            '      <script type="text/javascript" src="sticky.js"></script> <!--  JAVASCRIPT --> \r\n'
            '</head>\r\n'
            '<body>\r\n'
            '<div id="header">\r\n'
            '   <nav class="nav-main">\r\n'
            '       <div class="logo">Welcome</div>\r\n'
            '       <ul>\r\n'
            '         <li>\r\n'
            '         <a href="#" class="nav-item">Menu</a>\r\n'
            '         </li>\r\n'
            '         <li>\r\n'
            '         <a href="#" class="nav-item">Admin</a>\r\n'
            '         </li>\r\n'
            '         <li>\r\n'
            '         <a href="#" class="nav-item">Users</a>\r\n'
            '         </li>\r\n'
            '     </ul>\r\n'
            ' </nav>\r\n'
            '</div>\r\n'
            ' <div class="content">\r\n'
            '\r\n'
            ' </div>\r\n'
            '</body>\r\n'
            '</html>')
        f.close()
        f2 = open("YOUR_STUFF/sticky.css", "w")
        f2.write('body, html {\r\n' \
            'margin:0;\r\n'
            'font-family: "Lalezar", cursive;\r\n'
            'animation-name: page;\r\n'
            'height: 3000px;\r\n'
            '-webkit-animation-name: page; /* PAGE TRANSITION */\r\n'
            '-moz-animation-name: page;\r\n'
            'animation-duration: 1.0s;\r\n'
            '-webkit-animation-duration: 1.0s;\r\n'
            '-moz-animation-duration: 1.0s;\r\n'
            '}\r\n'
            '@keyframes page{\r\n'
            'from{\r\n'
            'opacity: 0;\r\n'
            '}to{\r\n'
            'opacity: 1.0;\r\n'
            '}\r\n'
            '}\r\n'
            '@-webkit-keyframes page{\r\n'
            'from{\r\n'
            'opacity: 0;\r\n'
            '}to{\r\n'
            'opacity: 1.0;\r\n'
            '}\r\n'
            '}\r\n'
            '#header{\r\n'
              'margin:0;\r\n'
              'z-index:40;\r\n'
            '}\r\n'
            '.drop{\r\n'
             'display:none;\r\n'
            ' z-index:20;\r\n'
            '}\r\n\r\n'
            '.nav-main {\r\n'
            'width: 100%;\r\n'
            'background-color: #f44336;\r\n'
            'height: 70px;\r\n'
            'color: #fff;\r\n'
            '}\r\n\r\n'
            '.logo {\r\n'
            'float: left;\r\n'
            'height: 40px;\r\n'
            'padding: 15px 30px;\r\n'
            'font-size: 2.5em;\r\n'
            'line-height: 40px;\r\n'
            '}\r\n\r\n'
            '.nav-main > ul {\r\n'
            'margin: 0;\r\n'
            'padding: 0;\r\n'
            'float: left;\r\n'
            'list-style-type: none;\r\n'
            '}\r\n\r\n'
            '.nav-main > ul > li {\r\n'
            'float: left;\r\n'
            '}\r\n\r\n'
            '.nav-item {\r\n'
            'display: inline-block;\r\n'
            'padding: 15px 20px;\r\n'
            'height: 40px;\r\n'
            'line-height: 40px;\r\n'
            'color: #fff;\r\n'
            'text-decoration: none;\r\n\r\n'
            '}\r\n'
            '.nav-item:hover{\r\n'
            'background-color: #b71c1c;\r\n'
            '}\r\n')
        f2.close()
        f3 = open("YOUR_STUFF/sticky.js", "w")
        f3.write('$(window).load(function(){\r\n' \
              '     $("#header").sticky({ topSpacing: 0 });\r\n'
            '});')
        f3.close()
        print("\033[1;32m\r\n[*] Template created succesfully... Don't forget to copy the \033[1;45m'src'\033[1;m\033[1;32m folder where you move the template! ;)\033[1;m\r\n")
    except:
            print ("\r\n\033[1;41m[!] Error... can't create the file\033[1;m\r\n")

def gridRes(): #### RESPONSIVE GRID DESIGN ####
    try :
     f = open("YOUR_STUFF/responsive.html", "w")
     f.write('<!DOCTYPE html> <1-- RESPONSIVE GRID LAYOUT -->\r\n'\
                    '<html>\r\n'
                    '<head>\r\n'
                    '	<meta name="viewport" content="width=device-width, initial-scale=1.0">\r\n'
                    '	<link rel="stylesheet" href="responsive.css" media="all">\r\n'
                    '	<link href="https://fonts.googleapis.com/css?family=Lalezar" rel="stylesheet">\r\n'
                    '</head>\r\n'
                    '<body>\r\n'
                    '	<div class="section group">\r\n'
                    '		<div class="col span_1_of_3">\r\n'
                    '		First column\r\n'
                    '		</div>\r\n'
                    '		<div class="col span_1_of_3">\r\n'
                    '		Second column\r\n'
                    '		</div>\r\n'
                    '		<div class="col span_1_of_3">\r\n'
                    '		Third column\r\n'
                    '		</div>\r\n'
                    '	</div>\r\n'
                    '	<div style="height:50px;padding-top:10px;"></div>\r\n'
                    '	<div class="section group">\r\n'
                    '		<div class="col span_2_of_3">\r\n'
                    '		First column\r\n'
                    '		</div>\r\n'
                    '		<div class="col span_1_of_3">\r\n'
                    '		Second column\r\n'
                    '		</div>\r\n'
                    '	</div>\r\n'
                    '	<div style="height:50px;padding-top:10px;"></div>\r\n'
                    '	<div class="section group">\r\n'
                    '		<div class="col span_3_of_3">\r\n'
                    '		First column\r\n'
                    '		</div>\r\n'
                    '	</div>\r\n'
                    '	<div style="height:50px;padding-top:10px;"></div>\r\n'
                    '	<div class="section group">\r\n'
                    '		<div class="col span_1_of_3">\r\n'
                    '		First column\r\n'
                    '		</div>\r\n'
                    '		<div class="col span_2_of_3">\r\n'
                    '		Second column\r\n'
                    '		</div>\r\n'
                    '	</div>\r\n'
                    '</body>\r\n'
                    '</html>')
     f.close()
     f2 = open("YOUR_STUFF/responsive.css", "w")
     f2.write('html, body { \r\n' \
                        '	font-family: "Lalezar", cursive;\r\n'
                        '	animation-name: page;\r\n'
                        '	-webkit-animation-name: page; /* PAGE TRANSITION */\r\n'
                        '	-moz-animation-name: page;\r\n'
                        '	animation-duration: 1.0s;\r\n'
                        '	-webkit-animation-duration: 1.0s;\r\n'
                        '	-moz-animation-duration: 1.0s;\r\n'
                        '	color: white;\r\n'
                        '}\r\n'
                        '@keyframes page{\r\n'
                        'from{\r\n'
                        'opacity: 0;\r\n'
                        '}to{\r\n'
                        'opacity: 1.0;\r\n'
                        '}\r\n'
                        '}\r\n'
                        '@-webkit-keyframes page{\r\n'
                        'from{\r\n'
                        'opacity: 0;\r\n'
                        '}to{\r\n'
                        'opacity: 1.0;\r\n'
                        '}\r\n\r\n'
                        '}\r\n'
                        '.section {\r\n'
                        '	clear: both;\r\n'
                        '	padding: 0px;\r\n'
                        '	margin: 0px;\r\n'
                        '}\r\n'
                        '.col {\r\n'
                        '	display: block;\r\n'
                        '	float:left;\r\n'
                        '	margin: 1% 0 1% 1.6%;\r\n'
                        '}\r\n'
                        '.col:first-child { margin-left: 0; }\r\n'
                        '.group:before,\r\n'
                        '.group:after {\r\n'
                        '	content:"";\r\n'
                        '	display:table;\r\n'
                        '}\r\n'
                        '.group:after {\r\n'
                        '	clear:both;\r\n'
                        '}\r\n'
                        '.group {\r\n'
                        '    zoom:1;\r\n'
                        '}\r\n'
                        '.span_3_of_3 {\r\n'
                        '	width: 100%;\r\n'
                        '	background-color: #b71c1c;\r\n'
                        '	text-align: center;\r\n'
                        '	padding: 1em 0;\r\n'
                        '}\r\n'
                        '.span_2_of_3 {\r\n'
                        '	width: 66.1%;\r\n'
                        '	background-color: #b71c1c;\r\n'
                        '	text-align: center;\r\n'
                        '	padding: 1em 0;\r\n'
                        '}\r\n'
                        '.span_1_of_3 {\r\n'
                        '	width: 32.2%;\r\n'
                        '	background-color: #b71c1c;\r\n'
                        '	text-align: center;\r\n'
                        '	padding: 1em 0;\r\n'
                        '}\r\n\r\n'
                        '@media only screen and (max-width: 480px) {\r\n'
                        '	.col { margin: 1% 0 1% 0%;}\r\n'
                        '	.span_3_of_3, .span_2_of_3, .span_1_of_3 { width: 100%; }\r\n'
                        '}')
     f2.close()
     print("\033[1;32m\r\n[*] Template created succesfully... Have fun! ;)\033[1;m\r\n")
    except:
            print ("\r\n\033[1;41m[!] Error... can't create the file\033[1;m\r\n")
